version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escooter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "15022:15022"
    depends_on:
      - db
    environment:
      # Note the use of the asyncpg driver in the connection URL.
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/escooter"

volumes:
  postgres_data:
